## **Image detection with CNN**

In [1]:
from keras.datasets import cifar10

In [2]:
import numpy as np

In [3]:
from keras.utils import to_categorical  
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.optimizers import SGD
from keras.layers import BatchNormalization

In [18]:
(x_train,y_train), (x_test,y_test) = cifar10.load_data()

In [16]:
print(x_test)
print(x_train)

[[[[158 112  49]
   [159 111  47]
   [165 116  51]
   ...
   [137  95  36]
   [126  91  36]
   [116  85  33]]

  [[152 112  51]
   [151 110  40]
   [159 114  45]
   ...
   [136  95  31]
   [125  91  32]
   [119  88  34]]

  [[151 110  47]
   [151 109  33]
   [158 111  36]
   ...
   [139  98  34]
   [130  95  34]
   [120  89  33]]

  ...

  [[ 68 124 177]
   [ 42 100 148]
   [ 31  88 137]
   ...
   [ 38  97 146]
   [ 13  64 108]
   [ 40  85 127]]

  [[ 61 116 168]
   [ 49 102 148]
   [ 35  85 132]
   ...
   [ 26  82 130]
   [ 29  82 126]
   [ 20  64 107]]

  [[ 54 107 160]
   [ 56 105 149]
   [ 45  89 132]
   ...
   [ 24  77 124]
   [ 34  84 129]
   [ 21  67 110]]]


 [[[235 235 235]
   [231 231 231]
   [232 232 232]
   ...
   [233 233 233]
   [233 233 233]
   [232 232 232]]

  [[238 238 238]
   [235 235 235]
   [235 235 235]
   ...
   [236 236 236]
   [236 236 236]
   [235 235 235]]

  [[237 237 237]
   [234 234 234]
   [234 234 234]
   ...
   [235 235 235]
   [235 235 235]
   [234 234

In [6]:
print(np.unique(y_train))

[0 1 2 3 4 5 6 7 8 9]


In [7]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [19]:
x_train = x_train/255.0
print(x_train)
x_test = x_test/255.0
print(x_test)


[[[[0.23137255 0.24313725 0.24705882]
   [0.16862745 0.18039216 0.17647059]
   [0.19607843 0.18823529 0.16862745]
   ...
   [0.61960784 0.51764706 0.42352941]
   [0.59607843 0.49019608 0.4       ]
   [0.58039216 0.48627451 0.40392157]]

  [[0.0627451  0.07843137 0.07843137]
   [0.         0.         0.        ]
   [0.07058824 0.03137255 0.        ]
   ...
   [0.48235294 0.34509804 0.21568627]
   [0.46666667 0.3254902  0.19607843]
   [0.47843137 0.34117647 0.22352941]]

  [[0.09803922 0.09411765 0.08235294]
   [0.0627451  0.02745098 0.        ]
   [0.19215686 0.10588235 0.03137255]
   ...
   [0.4627451  0.32941176 0.19607843]
   [0.47058824 0.32941176 0.19607843]
   [0.42745098 0.28627451 0.16470588]]

  ...

  [[0.81568627 0.66666667 0.37647059]
   [0.78823529 0.6        0.13333333]
   [0.77647059 0.63137255 0.10196078]
   ...
   [0.62745098 0.52156863 0.2745098 ]
   [0.21960784 0.12156863 0.02745098]
   [0.20784314 0.13333333 0.07843137]]

  [[0.70588235 0.54509804 0.37647059]
   [0.6

In [9]:
x_val=x_train[45000:50000]
y_val=y_train[45000:50000]

In [10]:
model = Sequential()

model.add(Conv2D(32,(3,3), activation='relu',kernel_initializer='he_uniform',padding='same',input_shape=(32,32,3)))
model.add(BatchNormalization())
model.add(Conv2D(32,(3,3), activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))

model.add(Conv2D(64,(3,3), activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(64,(3,3), activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))

model.add(Conv2D(128,(3,3), activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(BatchNormalization())
model.add(Conv2D(128,(3,3), activation='relu',kernel_initializer='he_uniform',padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(2,2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))

In [11]:
opt=SGD(lr=0.001, momentum=0.95)
model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])

In [12]:
history= model.fit(x_train[:45000], y_train[:45000],epochs=50, batch_size=64, validation_data=(x_val,y_val),verbose=2)

Epoch 1/50
704/704 - 8s - loss: 1.8323 - accuracy: 0.4319 - val_loss: 1.3636 - val_accuracy: 0.5306
Epoch 2/50
704/704 - 5s - loss: 1.2780 - accuracy: 0.5707 - val_loss: 1.0938 - val_accuracy: 0.6264
Epoch 3/50
704/704 - 5s - loss: 1.0828 - accuracy: 0.6295 - val_loss: 0.9442 - val_accuracy: 0.6734
Epoch 4/50
704/704 - 5s - loss: 0.9590 - accuracy: 0.6704 - val_loss: 0.9323 - val_accuracy: 0.6804
Epoch 5/50
704/704 - 5s - loss: 0.8850 - accuracy: 0.6941 - val_loss: 0.8336 - val_accuracy: 0.7198
Epoch 6/50
704/704 - 5s - loss: 0.8183 - accuracy: 0.7140 - val_loss: 0.7510 - val_accuracy: 0.7426
Epoch 7/50
704/704 - 5s - loss: 0.7591 - accuracy: 0.7362 - val_loss: 0.7306 - val_accuracy: 0.7472
Epoch 8/50
704/704 - 5s - loss: 0.7157 - accuracy: 0.7505 - val_loss: 0.7100 - val_accuracy: 0.7600
Epoch 9/50
704/704 - 5s - loss: 0.6851 - accuracy: 0.7612 - val_loss: 0.7083 - val_accuracy: 0.7598
Epoch 10/50
704/704 - 5s - loss: 0.6465 - accuracy: 0.7749 - val_loss: 0.6440 - val_accuracy: 0.7832

In [13]:
model_result = model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.6678 - accuracy: 0.8218
