# Isolation Forest in Credit Card Fraud Detection

In [ ]:
df=pd.read_csv("creditcard.csv")

In [ ]:
df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [ ]:
data=df.drop(labels="Class",axis=1)

In [ ]:
data.drop(labels='Time',axis=1,inplace=True)
data.shape
data.head()

V1        V2        V3        V4  ...       V26       V27       V28  Amount
0 -1.359807 -0.072781  2.536347  1.378155  ... -0.189115  0.133558 -0.021053  149.62
1  1.191857  0.266151  0.166480  0.448154  ...  0.125895 -0.008983  0.014724    2.69
2 -1.358354 -1.340163  1.773209  0.379780  ... -0.139097 -0.055353 -0.059752  378.66
3 -0.966272 -0.185226  1.792993 -0.863291  ... -0.221929  0.062723  0.061458  123.50
4 -1.158233  0.877737  1.548718  0.403034  ...  0.502292  0.219422  0.215153   69.99

[5 rows x 29 columns]

In [ ]:
target = df['Class']
target.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [ ]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
from sklearn.ensemble import IsolationForest
constamination=0.001

In [ ]:
model = IsolationForest(contamination=0.01,n_estimators=100,max_samples='auto',max_features=1.0, bootstrap=False, n_jobs=-1, random_state=42, verbose=0,behaviour="new")
model.fit(data)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_iforest.py:248: FutureWarning: 'behaviour' is deprecated in 0.22 and will be removed in 0.24. You should not pass or set this parameter.
  FutureWarning


IsolationForest(behaviour='new', bootstrap=False, contamination=0.01,
                max_features=1.0, max_samples='auto', n_estimators=100,
                n_jobs=-1, random_state=42, verbose=0, warm_start=False)

In [ ]:
df['iForest']=pd.Series(model.predict(data))
print(df['iForest'].value_counts())

 1    281958
-1      2849
Name: iForest, dtype: int64


In [ ]:
print(df)

            Time         V1         V2  ...  Amount  Class  iForest
0            0.0  -1.359807  -0.072781  ...  149.62      0        1
1            0.0   1.191857   0.266151  ...    2.69      0        1
2            1.0  -1.358354  -1.340163  ...  378.66      0        1
3            1.0  -0.966272  -0.185226  ...  123.50      0        1
4            2.0  -1.158233   0.877737  ...   69.99      0        1
...          ...        ...        ...  ...     ...    ...      ...
284802  172786.0 -11.881118  10.071785  ...    0.77      0       -1
284803  172787.0  -0.732789  -0.055080  ...   24.79      0        1
284804  172788.0   1.919565  -0.301254  ...   67.88      0        1
284805  172788.0  -0.240440   0.530483  ...   10.00      0        1
284806  172792.0  -0.533413  -0.189733  ...  217.00      0        1

[284807 rows x 32 columns]


In [ ]:
iForest = df['iForest'].values
Class = df['Class'].values

In [ ]:

#(tn, fp, fn, tp)


array([[     0,      0,      0],
       [  2552,      0, 281763],
       [   297,      0,    195]])

In [ ]:
iForest = np.where(iForest==1,0,1)

In [ ]:
np.unique(iForest,return_counts=True)

(array([0, 1]), array([281958,   2849]))

In [ ]:
np.unique(Class,return_counts=True)

(array([0, 1]), array([284315,    492]))

In [ ]:
count=0
normal=0

In [ ]:

np.unique(np.where((iForest==Class),True,False),return_counts=True)

(array([False,  True]), array([  2747, 282060]))

In [ ]:
print(confusion_matrix(Class,iForest))
print(classification_report(Class,iForest))

[[281763   2552]
 [   195    297]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00    284315
           1       0.10      0.60      0.18       492

    accuracy                           0.99    284807
   macro avg       0.55      0.80      0.59    284807
weighted avg       1.00      0.99      0.99    284807

